import React from "react";
import type { ReactNode } from "react";

import Head from "next/head";
import * as R from "ramda";

export function get<T>(obj: any, keyPath?: string, defaultValue?: T) {
  return R.pathOr(
    defaultValue,
    R.pipe(R.split(/[[\].]/), R.filter(Boolean))(keyPath)
  )(obj);
}

export default function Home({}) {
  const [] = React.useState<ReactNode>([]);
  return (
    <div className="container m-0 h-screen p-2 flex justify-center items-center flex-col">
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-red m-3">
        <div>App Name: {process.env.APP_NAME}</div>
        <div>App Version: {process.env.APP_VERSION}</div>
        <div>App Framework: {process.env.APP_FRAMEWORK}</div>
        <div>Stage Environment: {process.env.STAGE}</div>
        <div>Node Environment: {process.env.NODE_ENV}</div>
        <div>Last Modified: {process.env.LAST_MODIFIED}</div>
      </main>
    </div>
  );
}
